export const products = [
  {
    id: "g-001",
    name: "Standard Clear Float Glass",
    category: "Float Glass",
    thickness: 4,
    width: 244,
    height: 183,
    color: "Clear",
    coating: "None",
    certification: "None",
    edgeFinish: "Raw",
    pricePerSqm: 450,
    supplier: "Saint-Gobain Glass India",
    location: "Chennai",
    description: "Versatile, high-quality standard clear float glass for general interior applications. Offers superior optical clarity and flatness.",
    inStock: true,
    minOrderQty: 50
  },
  {
    id: "g-002",
    name: "Architectural Bronze Tinted Glass",
    category: "Float Glass",
    thickness: 6,
    width: 321,
    height: 225,
    color: "Bronze",
    coating: "None",
    certification: "IS 2835",
    edgeFinish: "Polished",
    pricePerSqm: 680,
    supplier: "Asahi India Glass Ltd (AIS)",
    location: "Delhi",
    description: "Bronze tinted float glass that absorbs solar radiation, reducing glare and heat transmission. Ideal for architectural facades.",
    inStock: true,
    minOrderQty: 100
  },
  {
    id: "g-003",
    name: "Heavy Duty Frosted Float",
    category: "Float Glass",
    thickness: 8,
    width: 200,
    height: 150,
    color: "Frosted",
    coating: "None",
    certification: "None",
    edgeFinish: "Raw",
    pricePerSqm: 850,
    supplier: "Gold Plus Glass Industry",
    location: "Roorkee",
    description: "A translucent frosted glass variant providing privacy while allowing natural light transmission. Excellent for partitions.",
    inStock: true,
    minOrderQty: 20
  },
  {
    id: "g-004",
    name: "Toughened Shower Enclosure Glass",
    category: "Tempered Glass",
    thickness: 8,
    width: 90,
    height: 210,
    color: "Clear",
    coating: "None",
    certification: "IS 2553",
    edgeFinish: "Polished",
    pricePerSqm: 1200,
    supplier: "Sisecam Flat Glass India",
    location: "Pune",
    description: "Highly durable tempered glass explicitly designed for humid environments like bathrooms. Offers 4-5 times more strength than standard float glass.",
    inStock: true,
    minOrderQty: 10
  },
  {
    id: "g-005",
    name: "Acoustic PVB Laminated Glass",
    category: "Laminated Glass",
    thickness: 8.8,
    width: 244,
    height: 183,
    color: "Clear",
    coating: "UV Protection",
    certification: "IS 2553",
    edgeFinish: "Polished",
    pricePerSqm: 2100,
    supplier: "GSC Glass Ltd",
    location: "Noida",
    description: "Features a specialized PVB interlayer (4+0.8+4mm) for superior sound insulation and safety. UV-blocking interlayer protects from harmful radiation — ideal for balcony railings and high-wind facades.",
    inStock: true,
    minOrderQty: 30
  },
  {
    id: "g-006",
    name: "Low-E DGU Facade Unit",
    category: "Insulated Glass Unit",
    thickness: 24,
    width: 150,
    height: 250,
    color: "Tinted",
    coating: "Low-E",
    certification: "EN 12150",
    edgeFinish: "Polished",
    pricePerSqm: 3500,
    supplier: "Toughglass India Pvt Ltd",
    location: "Mumbai",
    description: "Premium Double Glazed Unit (6+12Air+6mm) featuring advanced Low-E coating. Exceptional thermal efficiency for commercial high-rises.",
    inStock: false,
    minOrderQty: 50
  },
  {
    id: "g-007",
    name: "Solar Control Blue Tint Tempered",
    category: "Tempered Glass",
    thickness: 6,
    width: 244,
    height: 183,
    color: "Blue",
    coating: "UV Protection",
    certification: "IS 2553",
    edgeFinish: "Beveled",
    pricePerSqm: 1450,
    supplier: "Asahi India Glass Ltd (AIS)",
    location: "Bawal",
    description: "Aesthetically pleasing blue-tinted tempered glass with integrated UV protection. Strikes a balance between cooling and natural light.",
    inStock: true,
    minOrderQty: 40
  },
  {
    id: "g-008",
    name: "Oversized Storefront Tempered",
    category: "Tempered Glass",
    thickness: 10,
    width: 300,
    height: 300,
    color: "Clear",
    coating: "Anti-reflective",
    certification: "EN 12150",
    edgeFinish: "Polished",
    pricePerSqm: 2200,
    supplier: "Saint-Gobain Glass India",
    location: "Sriperumbudur",
    description: "Large format toughened glass with anti-reflective coating for maximum visibility. Ideal for luxury retail storefronts.",
    inStock: true,
    minOrderQty: 10
  },
  {
    id: "g-009",
    name: "Safety Wardrobe Mirror",
    category: "Mirror",
    thickness: 5,
    width: 122,
    height: 244,
    color: "Clear",
    coating: "None",
    certification: "None",
    edgeFinish: "Beveled",
    pricePerSqm: 950,
    supplier: "Gujarat Guardian Limited",
    location: "Ankleshwar",
    description: "Copper-free silver mirror backed with a safety film to prevent shattering. Provides pristine reflection with elegant beveled edges.",
    inStock: true,
    minOrderQty: 25
  },
  {
    id: "g-010",
    name: "Security Bullet-Resistant Laminated",
    category: "Laminated Glass",
    thickness: 18,
    width: 120,
    height: 200,
    color: "Clear",
    coating: "UV Protection",
    certification: "IS 2553",
    edgeFinish: "Polished",
    pricePerSqm: 8500,
    supplier: "Duratuf Glass Industries",
    location: "Delhi",
    description: "Multi-layered high-security laminated glass. Engineered for banks and high-value retail applications requiring stringent impact resistance.",
    inStock: false,
    minOrderQty: 5
  },
  {
    id: "g-011",
    name: "Aluminium Glass Door Patch Fitting",
    category: "Aluminium Hardware",
    thickness: 0,
    width: 16,
    height: 5,
    color: "Clear",
    coating: "None",
    certification: "None",
    edgeFinish: "Polished",
    pricePerSqm: 1800,
    supplier: "Ozone Overseas",
    location: "Gurugram",
    description: "Premium stainless-steel finished aluminium patch fitting for frameless glass doors. Ensures smooth operation and architectural elegance.",
    inStock: true,
    minOrderQty: 50
  },
  {
    id: "g-012",
    name: "Minimalist Window Profile Frame",
    category: "Aluminium Hardware",
    thickness: 2,
    width: 5,
    height: 300,
    color: "Clear",
    coating: "None",
    certification: "None",
    edgeFinish: "Raw",
    pricePerSqm: 650,
    supplier: "Jindal Aluminium Ltd",
    location: "Bangalore",
    description: "Extruded aluminium window profiles offering slim sightlines for modern architecture. Corrosion-resistant and highly structurally sound.",
    inStock: true,
    minOrderQty: 100
  },
  {
    id: "g-013",
    name: "5+12+5 Energy Efficient DGU",
    category: "Insulated Glass Unit",
    thickness: 22,
    width: 120,
    height: 200,
    color: "Clear",
    coating: "Low-E",
    certification: "IS 2553",
    edgeFinish: "Polished",
    pricePerSqm: 2900,
    supplier: "FUSO Glass India Pvt Ltd",
    location: "Chennai",
    description: "Standard 5+12+5mm Double Glazed Unit with 12mm argon-filled air gap and Low-E coating. Delivers excellent thermal insulation for energy-efficient windows up to 2m height.",
    inStock: true,
    minOrderQty: 30
  },
  {
    id: "g-014",
    name: "Clear Tempered Office Partition Glass",
    category: "Tempered Glass",
    thickness: 6,
    width: 200,
    height: 120,
    color: "Clear",
    coating: "None",
    certification: "IS 2553",
    edgeFinish: "Polished",
    pricePerSqm: 1100,
    supplier: "Sisecam Flat Glass India",
    location: "Pune",
    description: "6mm toughened clear glass engineered specifically for office cabin partitions and interior dividers. Polished edges ensure a seamless, frameless look with full IS 2553 safety compliance.",
    inStock: true,
    minOrderQty: 20
  },
  {
    id: "g-015",
    name: "Budget 4mm Residential Window Float",
    category: "Float Glass",
    thickness: 4,
    width: 180,
    height: 120,
    color: "Clear",
    coating: "None",
    certification: "None",
    edgeFinish: "Raw",
    pricePerSqm: 380,
    supplier: "Gold Plus Glass Industry",
    location: "Roorkee",
    description: "Economy-grade 4mm clear float glass for residential windows and interior glazing. Best suited for large-volume orders in housing projects where cost-efficiency is paramount.",
    inStock: true,
    minOrderQty: 100
  }
];
